services:
  prometheus:
    image: prom/prometheus
    volumes:
      # Absolyut yo'l bilan mount qilamiz
      - /c/Abbos/BRB/Grafana/src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
